version: "3.9"
services:
  postgres:
    container_name: simple-bank-db
    image: postgres:14-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  api:
    container_name: simple-bank-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - 8080:8080
      - 6868:6868
    env_file:
      - ./.env
    environment:
      DB_URI: $DB_URI
    restart: always
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for-2.2.3/wait-for", "postgres:5432", "--", "/app/scripts/start.sh" ]
    command: [ "air", "server", "--port 8080" ]

volumes:
  postgres_volume:
