FROM golang:1.20-alpine3.17

WORKDIR /app

COPY . .

RUN apk --update --no-cache add build-base curl

RUN curl -L https://github.com/eficode/wait-for/archive/refs/tags/v2.2.4.tar.gz | tar xvz
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz

RUN go mod tidy && go mod download && go mod verify

RUN go install github.com/go-delve/delve/cmd/dlv@v1.20.2
RUN go install github.com/cosmtrek/air@v1.43.0

# Set migrations in the main directory.
COPY src/database/migrations ./migrations

EXPOSE 8080 9090
