name: ci-test

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

env:
  DB_DRIVER: ${{secrets.DB_DRIVER}}
  DB_URI: ${{secrets.DB_URI}}
  POSTGRES_DB: ${{secrets.POSTGRES_DB}}
  POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Create reference for the app.env file
        run: |
          cat <<EOF > app.env
          # Database settings to work locally.
          # Uncomment and set the respective values for these variables in a `.env` file,
          # these variables will be taken by the `docker-compose.yaml` file to compose the database container.
          #POSTGRES_PASSWORD=<THE_POSTGRES_PASSWORD>

          # App settings.
          # These values will be taken by default, they can be replaced by environment variables.
          DB_DRIVER=<THE_DB_DRIVER>
          DB_URI=<THE_DB_URI>
          SERVER_ADDRESS=<THE_SERVER_ADDRESS>

          # Authentication settings.
          TOKEN_SYMMETRIC_KEY=<THE_TOKEN_SYMMETRIC_KEY>
          TOKEN_DURATION=<THE_TOKEN_DURATION>
          EOF

      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Run migrations
        run: make migrateup

      - name: Run tests
        run: make test
