name: "Run tests"

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

env:
  DB_DRIVER: ${{ secrets.DB_DRIVER }}
  DB_URI: ${{ secrets.DB_URI }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  TOKEN_DURATION: ${{ secrets.TOKEN_DURATION }}
  TOKEN_SYMMETRIC_KEY: ${{ secrets.TOKEN_SYMMETRIC_KEY }}
  REFRESH_TOKEN_DURATION: ${{ secrets.REFRESH_TOKEN_DURATION }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:15.2-alpine3.17
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
          check-latest: true
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Download Go modules
        run: go mod download

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

      - name: Run migrations
        run: make migrateUp

      - name: Run tests
        run: make test
